# -*- coding: utf-8 -*-
"""XML to CSV

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cReZU0EArOM1HL1Ez5fxcqYsTQHQLsS6
"""

!pip install xmltodict

import xmltodict, csv

csvfile = open("imageData.csv",'w',encoding='utf-8')
csvfile_writer = csv.writer(csvfile)

Standard = "image_"
idx = 0
totalImages = 440
dataTypeRange = {"TRAIN":(0,360), "VALIDATION":(360,400), "TEST":(400,440)}

def xml_to_csv():
  
  for key in dataTypeRange:
    from_, to_ = dataTypeRange[key]
    for i in range(from_, to_):

      filename = Standard + str(i) + ".xml"  
      # PARSE XML FILE
      with open(filename) as xmlfile:
          xml = xmltodict.parse(xmlfile.read())

      path = xml["annotation"]["path"]
      
      try:  
        for obj in xml["annotation"]["object"]:  
          
          tag = obj["name"]
          dimensions = {"xmin" : 0, "xmax" : 0, "ymin" : 0, "ymax" : 0}
          for dim in ["xmin", "xmax", "ymin", "ymax"]:
            dimensions[dim] = obj["bndbox"][dim]

          csv_line = [key, path, tag, dimensions["xmin"], dimensions["xmax"], None , None , dimensions["ymin"], dimensions["ymax"], None,]
          #print(csv_line)
          csvfile_writer.writerow(csv_line)
      

      except:
        obj = xml["annotation"]["object"]
        tag = obj["name"]
        dimensions = {"xmin" : 0, "xmax" : 0, "ymin" : 0, "ymax" : 0}
        for dim in ["xmin", "xmax", "ymin", "ymax"]:
          dimensions[dim] = obj["bndbox"][dim]

        csv_line = [key, path, tag, dimensions["xmin"], dimensions["xmax"], None, None , dimensions["ymin"], dimensions["ymax"], None,]
        #print(csv_line) 
        csvfile_writer.writerow(csv_line)
      
      # ADD A NEW ROW TO CSV FILE

xml_to_csv()
csvfile.close()